# Generated by Django 3.0.3 on 2020-06-19 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absentelkom', '0002_remove_tbl_absen_ami_id_jampel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_absen_ami',
            name='id_jampel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='absentelkom.Tbl_jampel'),
        ),
    ]
