# Generated by Django 3.0.3 on 2020-07-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absentelkom', '0003_tbl_absen_ami_id_jampel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_absen_ami',
            name='id_absen_ami',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
