from django.urls import path
from . import views

urlpatterns = [
    path('', views.to_login_views, name="to_login_views"),
    path('to_login_guru_views', views.to_login_guru_views, name="to_login_guru_views"),
    path('login_views', views.login_views, name="login_views"),
    path('to_acara_views', views.to_acara_views, name="to_acara_views"),
    path('absensave_views', views.absensave_views, name="absensave_views"),
    path('to_ami_views', views.to_ami_views, name="to_ami_views"),
    path('login_guru_views', views.login_guru_views, name="login_guru_views"),
    path('to_acara_walas_views', views.to_acara_walas_views, name="to_acara_walas_views"),
    path('to_pilihkelas_walas_views', views.to_pilihkelas_walas_views, name="to_pilihkelas_walas_views"),
    path('to_validasi_walas_views', views.to_validasi_walas_views, name="to_validasi_walas_views"),
    path('to_guru_admin_views', views.to_guru_admin_views, name="to_guru_admin_views"),
    path('to_siswa_admin_views', views.to_siswa_admin_views, name="to_siswa_admin_views"),
    path('to_kelas_admin_views', views.to_kelas_admin_views, name="to_kelas_admin_views"),
    path('to_acara_admin_views', views.to_acara_admin_views, name="to_acara_admin_views"),
    path('to_dashboard_admin_views', views.to_dashboard_admin_views, name="to_acara_dashboard_views"),
    path('to_editguru_admin_views', views.to_editguru_admin_views, name="to_editguru_admin_views"),
    path('to_editsiswa_admin_views', views.to_editsiswa_admin_views, name="to_editsiswa_admin_views"),
    path('to_editkelas_admin_views', views.to_editkelas_admin_views, name="to_editkelas_admin_views"),
    path('to_editacara_admin_views', views.to_editacara_admin_views, name="to_editacara_admin_views"),
    path('editguru_admin_views', views.editguru_admin_views, name="editguru_admin_views"),
    path('editsiswa_admin_views', views.editsiswa_admin_views, name="editsiswa_admin_views"),
    path('editkelas_admin_views', views.editkelas_admin_views, name="editkelas_admin_views"),
    path('editacara_admin_views', views.editacara_admin_views, name="editacara_admin_views"),
    path('to_tambahguru_admin_views', views.to_tambahguru_admin_views, name="to_tambahguru_admin_views"),
    path('tambahguru_admin_views', views.tambahguru_admin_views, name="tambahguru_admin_views"),
    path('hapusguru_admin_views', views.hapusguru_admin_views, name="hapusguru_admin_views"),
    path('to_tambahsiswa_admin_views', views.to_tambahsiswa_admin_views, name="to_tambahsiswa_admin_views"),
    path('tambahsiswa_admin_views', views.tambahsiswa_admin_views, name="tambahsiswa_admin_views"),
    path('hapussiswa_admin_views', views.hapussiswa_admin_views, name="hapussiswa_admin_views"),
    path('to_tambahkelas_admin_views', views.to_tambahkelas_admin_views, name="to_tambahkelas_admin_views"),
    path('tambahkelas_admin_views', views.tambahkelas_admin_views, name="tambahkelas_admin_views"),
    path('hapuskelas_admin_views', views.hapuskelas_admin_views, name="hapuskelas_admin_views"),
    path('to_tambahacara_admin_views', views.to_tambahacara_admin_views, name="to_tambahacara_admin_views"),
    path('tambahacara_admin_views', views.tambahacara_admin_views, name="tambahacara_admin_views"),
    path('hapusacara_admin_views', views.hapusacara_admin_views, name="hapusacara_admin_views"),
    path('laporankelas_admin_views', views.laporankelas_admin_views, name="laporankelas_admin_views"),
    path('laporantanggal_admin_views', views.laporantanggal_admin_views, name="laporantanggal_admin_views"),
    path('validasi_views', views.validasi_views, name="validasi_views"),
    path('ami_validasi_views', views.ami_validasi_views, name="ami_validasi_views"),
]